FROM php:8.1-fpm-alpine

WORKDIR /var/app

RUN apk update && apk add \
    build-base \
    libzip-dev \
#    php8-xsl \
    libxslt-dev \
    vim

RUN docker-php-ext-install pdo_mysql zip xsl


COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN addgroup -g 1000 -S www && \
    adduser -u 1000 -S www -G www

USER www

COPY --chown=www:www . /var
RUN cd /var/app && composer install --prefer-dist && composer dump-autoload
EXPOSE 9000
